version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: hospital-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: hospital-keycloak
    command: ["start-dev", "--http-port=8080", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./demo-realm.json:/opt/keycloak/data/import/demo-realm.json:ro
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
    container_name: hospital-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/hospital_analytics}
    ports:
      - "5050:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      args:
        REACT_APP_KEYCLOAK_URL: http://localhost:8080
        REACT_APP_KEYCLOAK_REALM: demo
        REACT_APP_KEYCLOAK_CLIENT_ID: demo-client
        REACT_APP_API_BASE_URL: http://localhost:5050
    container_name: hospital-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - keycloak

volumes:
  mongo_data:
    driver: local
