apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: hospital-web-app
type: Opaque
data:
  uri: bW9uZ29kYitzcnY6Ly92cWgwNDA5MjAwNDphZG1pbkBjbHVzdGVyMC5ubmhuZGFlLm1vbmdvZGIubmV0L2hvc3BpdGFsX2FuYWx5dGljcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
type: Opaque
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
